% make a red/blue colormap with nrblevels number of different levels

function rstring = make_rbcmap(nrblevels)

if nargin < 1
    nrblevels=1024;
end

rbcmaplevels=11; % this is maximum resolution generated by matlab
keymap=redbluecmap(rbcmaplevels);
interpFactor=ceil(nrblevels/rbcmaplevels);
reallevels=rbcmaplevels*interpFactor;

% interpolate the matlab-generated r/b cmap to the desired resolution 
tdumb=1:rbcmaplevels;
tintdumb=linspace(1,rbcmaplevels,reallevels);
rstring=zeros(reallevels,3);
for i=1:3
    rstring(:,i)=interp1(tdumb,keymap(:,i),tintdumb);
end

end