IOOBJ = $(addprefix ./IO/, input.o readinfo.o passinfo.o check.o output.o)
DOMOBJ = $(addprefix ./domain/, domain.o ghosts.o pass_fields.o)
UTILSOBJ = $(addprefix ./utils/, RNG.o)
PUSHOBJ = $(addprefix ./pusher/, boris.o)
B_PARTICLEOBJ = bc_p_MPI.o bc_p_periodic.o bc_p_reflecting.o
BOUNDARYOBJ = $(addprefix ./boundaries/, boundary_particles.o bc_factory.o \
			  $(addprefix b_particles/, $(B_PARTICLEOBJ)))
GRIDOBJ = $(addprefix ./grid/, grid.o oGrid.o spookyGrid.o)
PARTOBJ = $(addprefix ./particles/, particle.o particle_handler.o interpolate.o deposit.o)
POISSONOBJ = $(addprefix ./poisson/, poisson.o)

OBJ = $(IOOBJ) $(DOMOBJ) $(UTILSOBJ) $(PUSHOBJ) $(BOUNDARYOBJ) $(GRIDOBJ) $(PARTOBJ) $(POISSONOBJ) main.o
