IO = input.o readinfo.o passinfo.o check.o output.o hdf5io.o
IOTEST = input.o readinfo.o passinfo.o
DOM = domain.o resolve.o
UTIL = RNG.o evaluateGaussianPulse.o
PUSH = boris.o relativisticBoris.o
GRID = grid.o oGrid.o spookyGrid.o estaticBC.o lightBC.o
POISSON = poisson.o convertFields.o poissonBC.o
PART = particle.o particle_handler.o interpolate.o deposit.o
BC_PART = bc_p_MPI.o bc_p_periodic.o bc_p_reflecting.o
BC_FIELD = bc_f_MPI.o bc_f_periodic.o bc_f_external.o 
BC = particles_boundary.o particle_bc_factory.o \
     field_bc_factory.o

IOOBJ = $(addprefix ./IO/, $(IO))
IOTESTOBJ = $(addprefix ./IO/, $(IOTEST))
DOMOBJ = $(addprefix ./domain/, $(DOM))
UTILSOBJ = $(addprefix ./utils/, $(UTIL))
PUSHOBJ = $(addprefix ./pusher/, $(PUSH))
GRIDOBJ = $(addprefix ./grid/, $(GRID))
POISSONOBJ = $(addprefix ./poisson/,$(POISSON))
PARTOBJ = $(addprefix ./particles/, $(PART))
BOUNDARYOBJ = $(addprefix ./boundaries/, $(BC) \
		$(addprefix b_particles/, $(BC_PART)) \
		$(addprefix b_fields/, $(BC_FIELD)))


OBJ = $(IOOBJ) $(DOMOBJ) $(UTILSOBJ) $(PUSHOBJ) $(BOUNDARYOBJ) $(GRIDOBJ) $(PARTOBJ) $(POISSONOBJ) main.o
OBJTEST = $(IOOBJ) $(DOMOBJ) $(UTILSOBJ) $(PUSHOBJ) $(BOUNDARYOBJ) $(GRIDOBJ) $(PARTOBJ) $(POISSONOBJ)
OBJ_PAR = $(OBJ:.o=_par.o)
OBJTEST_PAR = $(OBJTEST:.o=_par.o)
